version: '3'

services:
 db:
   image: mysql:latest
   restart: on-failure
   command: --default-authentication-plugin=mysql_native_password
   environment:
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_DATABASE: mstore
    MYSQL_USER: root
    MYSQL_PASSWORD: pass
   ports:
    - "3306:3306"
   healthcheck:
    interval: 15s
    timeout: 15s
    retries: 10
 java-web:
   image: nmartinezs2017/webapp10
   restart: always
   links:
    - db
   depends_on:
    - db
   ports: 
    - "8443:8443"
   environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://db/mstore?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: pass